#!/bin/bash
# usbmount needs to be installed in order to use this.
# Put this file or create a link to it under /etc/usbmount/mount.d.
# Call the file 99-sync_music
if [[ $UM_DEVICE == "/dev/sdb2" ]]; then
	rsync -Phrtv --modify-window=1 --delete-before /home/ubuntu/media/music/ $UM_MOUNTPOINT/Music &> /home/ubuntu/sync_log
	rsync -Phrtv --modify-window=1 --delete-before /home/ubuntu/media/Playlists/ $UM_MOUNTPOINT/Playlists &>> /home/ubuntu/sync_log
	echo "Syncing..." >> /home/ubuntu/sync_log
	ipod-time-sync $UM_DEVICE "America/New_York"
	sync
	echo "Done Syncing..." >> /home/ubuntu/sync_log
	echo "Ejecting..." >> /home/ubuntu/sync_log
	eject $UM_DEVICE
	echo "${UM_DEVICE} Ejected..." >> /home/ubuntu/sync_log
	echo "done!" >> /home/ubuntu/sync_log
fi
